services:
  redis:
    image: redis:7-alpine
    container_name: redis_weather
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./src/services/storage/redis:/data

  fastapi_weather_api:
    build: . # builder le dossier actuel pour le service api
    image: weather-api:latest  # nom de l'image de l'api
    container_name: weather-api
    ports:
      - "8025:8025"
    depends_on:
      - redis
